import { useState } from "react";
import { addHistoryRecord } from "../lib/localHistory";
import { 
  Calculator, 
  Copy, 
  Download, 
  Save, 
  Check, 
} from "lucide-react";

export default function GstCalculator() {
  const [amount, setAmount] = useState<string>("1000");
  const [gstRate, setGstRate] = useState<number>(18);
  const [calcType, setCalcType] = useState<"add" | "remove">("add");
  
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);
  const [savingLoading, setSavingLoading] = useState(false);

  const rates = [3, 5, 12, 18, 28];

  // Mathematical equations
  const amt = parseFloat(amount) || 0;
  const gstAmount = calcType === "add" 
    ? amt * (gstRate / 100) 
    : amt - (amt * (100 / (100 + gstRate)));

  const finalAmount = calcType === "add"
    ? amt + gstAmount
    : amt;

  const originalAmount = calcType === "add"
    ? amt
    : amt - gstAmount;

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
      minimumFractionDigits: 2,
    }).format(val);
  };

  const handleCopy = () => {
    const textFormat = 
      `--- GST Calculation Report (ToolVerse) ---\n` +
      `Original Amount: ${formatCurrency(originalAmount)}\n` +
      `GST Rate: ${gstRate}%\n` +
      `Calculation Type: ${calcType === "add" ? "Add GST (+)" : "Remove GST (-)"}\n` +
      `GST Amount: ${formatCurrency(gstAmount)}\n` +
      `Final Net Amount: ${formatCurrency(finalAmount)}\n` +
      `-----------------------------------------`;
    
    navigator.clipboard.writeText(textFormat);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const textFormat = 
      `=========================================\n` +
      `             GST CALCULATION REPORT      \n` +
      `                  TOOLVERSE              \n` +
      `=========================================\n` +
      `Timestamp: ${new Date().toLocaleString()}\n` +
      `Calculation Type: ${calcType === "add" ? "Inclusive Add (+)" : "Exclusive Remove (-)"}\n` +
      `-----------------------------------------\n` +
      `Original Amount:   ${formatCurrency(originalAmount)}\n` +
      `GST Rate:          ${gstRate}%\n` +
      `GST Calculated:    ${formatCurrency(gstAmount)}\n` +
      `-----------------------------------------\n` +
      `FINAL TOTAL NET:   ${formatCurrency(finalAmount)}\n` +
      `=========================================\n` +
      `Generated by ToolVerse (All-in-One Smart Tools)`;

    const fileBlob = new Blob([textFormat], { type: "text/plain;charset=utf-8" });
    const fileUrl = URL.createObjectURL(fileBlob);
    const linkElement = document.createElement("a");
    linkElement.href = fileUrl;
    linkElement.download = `ToolVerse_GST_${amount || "calc"}.txt`;
    linkElement.click();
    URL.revokeObjectURL(fileUrl);
  };

  const handleSaveToHistory = async () => {
    setSavingLoading(true);
    setSaved(false);
    try {
      addHistoryRecord("gst_history", {
        toolName: "GST Calculator",
        amount: amt,
        gstRate: gstRate,
        gstAmount: parseFloat(gstAmount.toFixed(2)),
        finalAmount: parseFloat(finalAmount.toFixed(2)),
        calculationType: calcType,
      });
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    } catch (err) {
      console.error("Firestore Save Error:", err);
    } finally {
      setSavingLoading(false);
    }
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl backdrop-blur-md">
      <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-800">
        <div className="w-10 h-10 bg-indigo-500/10 rounded-xl flex items-center justify-center text-indigo-400">
          <Calculator className="w-5 h-5" />
        </div>
        <div>
          <h2 className="text-xl font-bold font-display text-white">GST Calculator</h2>
          <p className="text-xs text-slate-400">Calculate inclusive or exclusive GST effortlessly</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Left Side: Inputs */}
        <div className="space-y-5">
          {/* Amount input */}
          <div>
            <label className="block text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2">
              Base Amount (INR)
            </label>
            <div className="relative">
              <span className="absolute left-4 top-3 text-slate-500 font-bold">₹</span>
              <input
                type="number"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                placeholder="Enter base amount"
                className="w-full pl-8 pr-4 py-3 rounded-xl bg-slate-950 border border-slate-800 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-slate-100 placeholder-slate-600 text-sm outline-none transition-all"
              />
            </div>
          </div>

          {/* Calc Type Toggle */}
          <div>
            <label className="block text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2">
              Calculation Type
            </label>
            <div className="grid grid-cols-2 gap-3">
              <button
                type="button"
                onClick={() => setCalcType("add")}
                className={`py-2.5 px-4 rounded-xl text-xs font-bold transition-all border outline-none ${
                  calcType === "add"
                    ? "bg-indigo-600 border-indigo-500 text-white shadow-md shadow-indigo-950/40"
                    : "bg-slate-950 border-slate-800 hover:border-slate-700 text-slate-400 hover:text-slate-200"
                }`}
              >
                Add GST (+)
              </button>
              <button
                type="button"
                onClick={() => setCalcType("remove")}
                className={`py-2.5 px-4 rounded-xl text-xs font-bold transition-all border outline-none ${
                  calcType === "remove"
                    ? "bg-indigo-600 border-indigo-500 text-white shadow-md shadow-indigo-950/40"
                    : "bg-slate-950 border-slate-800 hover:border-slate-700 text-slate-400 hover:text-slate-200"
                }`}
              >
                Remove GST (-)
              </button>
            </div>
          </div>

          {/* GST rate selection */}
          <div>
            <label className="block text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2">
              GST Percentage (%)
            </label>
            <div className="grid grid-cols-5 gap-2">
              {rates.map((rate) => (
                <button
                  key={rate}
                  type="button"
                  onClick={() => setGstRate(rate)}
                  className={`py-3 px-2 rounded-lg text-xs font-bold transition-all border outline-none ${
                    gstRate === rate
                      ? "bg-indigo-600 border-indigo-500 text-white shadow-sm"
                      : "bg-slate-950 border-slate-800 hover:border-slate-700 text-slate-400 hover:text-slate-200"
                  }`}
                >
                  {rate}%
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Side: Outputs Display & Actions */}
        <div className="flex flex-col justify-between p-6 rounded-2xl bg-slate-950 border border-slate-800/80">
          <div className="space-y-4">
            <h3 className="text-xs font-bold uppercase tracking-widest text-slate-500 mb-2">Calculation Results</h3>

            {/* Original Net Amount */}
            <div className="flex justify-between items-center py-2.5 border-b border-slate-800/60 text-sm">
              <span className="text-slate-400">Original Amount</span>
              <span className="text-slate-200 font-mono font-medium">{formatCurrency(originalAmount)}</span>
            </div>

            {/* GST Output */}
            <div className="flex justify-between items-center py-2.5 border-b border-slate-800/60 text-sm">
              <span className="text-slate-400 flex items-center gap-1.5">
                GST Calculated <span className="px-1.5 py-0.5 rounded bg-slate-800 text-[10px] text-indigo-400 font-bold">{gstRate}%</span>
              </span>
              <span className="text-indigo-400 font-mono font-bold">+{formatCurrency(gstAmount)}</span>
            </div>

            {/* Grand Total output */}
            <div className="flex justify-between items-end pt-4 pb-2">
              <span className="text-slate-400 text-sm font-semibold">Grand Final Amount</span>
              <span className="text-2xl font-extrabold text-white font-mono tracking-tight">{formatCurrency(finalAmount)}</span>
            </div>
          </div>

          {/* Action Row */}
          <div className="grid grid-cols-3 gap-2 mt-6">
            <button
              onClick={handleCopy}
              className="py-2.5 px-3 rounded-lg border border-slate-800 hover:border-slate-700 bg-slate-900 hover:bg-slate-850 text-slate-300 hover:text-white transition-all text-xs font-semibold flex items-center justify-center gap-1.5"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  <span className="hidden sm:inline">Copied</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  <span className="hidden sm:inline">Copy</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownload}
              className="py-2.5 px-3 rounded-lg border border-slate-800 hover:border-slate-700 bg-slate-900 hover:bg-slate-850 text-slate-300 hover:text-white transition-all text-xs font-semibold flex items-center justify-center gap-1.5"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Download</span>
            </button>

            <button
              onClick={handleSaveToHistory}
              disabled={savingLoading}
              className="py-2.5 px-3 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs transition-all flex items-center justify-center gap-1.5 disabled:opacity-50"
            >
              {saved ? (
                <>
                  <Check className="w-4 h-4 text-emerald-300 animate-bounce" />
                  <span className="hidden sm:inline">Saved</span>
                </>
              ) : (
                <>
                  <Save className="w-4 h-4" />
                  <span className="hidden sm:inline">{savingLoading ? "Saving" : "SaveDB"}</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
